---
title: "Cytokine Profile in Infertile Women"
author: "Usman"
date: "2023-12-18"
output: 
  html_document: 
    toc: yes
    number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(janitor)
library(tidyverse)
library(dplyr)
library(MASS)
library(factoextra)
Chlamydia_Venn <- read_excel("C:/Users/Usman Ola/Downloads/Chlamydia Trichomatis.xlsx")
Chlamydia_logistic_reg <- clean_names(Chlamydia_Venn)
names(Chlamydia_logistic_reg) # All variables names are automagically cleaned!
newdata<-Chlamydia_logistic_reg[!Chlamydia_logistic_reg$how_long_7=="Nil",]%>%
  mutate(age_cat=cut(age,
                           breaks = c(0,35,Inf),
                           labels = c("<35",">35")),
          Marital_dur=ifelse(how_long_7=="1","First_Child","Children"),
         Marital_cat=cut(as.numeric(how_long_7),
                         c(0,10,20,30,Inf),
                         c("≤10","11-20","21-30",">30")),
         Times_mar=case_when(how_times=="Fouth"~">Two",
                             how_times=="Third"~">Two",
                             how_times=="First"~"first",
                             how_times=="Second"~"second"),
         wom_edu=str_replace(level_edu,"p","P"),
         husband_occ=case_when(
           husb_occ=="Leccturer"~"Lecturer",
           husb_occ=="Teacher"~"Lecturer",
           husb_occ=="Civil Serv"~"Civil_ser",
           husb_occ=="Lecturer"~"Lecturer",
           husb_occ=="Civil serv"~"Civil_ser",
           husb_occ=="Publicserv"~"Civil_ser",
           husb_occ=="Civilserv"~"Civil_ser",
           husb_occ=="Bussiness"~"Bussines",
           husb_occ=="Business"~"Bussines",
           husb_occ=="Carpenter"~"Artisan",
           husb_occ=="Artisan"~"Artisan",
           husb_occ=="Farmer"~"Farmer",
           TRUE~"others"),
         fam_type=str_replace_all(family_typ,c("mono"="Mono")),
         woman_occ=case_when(
           occup=="Teacher"~"Teacher",
           occup=="teacher"~"Teacher",
           occup=="Civil Serv"~"Civil_ser",
           occup=="House wife"~"House_wife",
           occup=="Civil serv"~"Civil_ser", 
           occup=="Civilserv"~"Civil_ser",
           occup=="Student"~"Student",
           occup=="Tailor"~"Artisan",
           occup=="Artisan"~"Artisan", 
           occup=="Farmer"~"Farmer",
           TRUE~"others"),
         any_preg=recode(any_preg,"No"="Primary_infert",
                         "Yes"="secondary_infert"),
         how_many=recode(
           how_many,
           "Eight"=8,
           "Five"=5,
           "Four"=4,
           "Nil"=12,
           "Once"=1,
           "One"=1,
           "Seven"=7,
           "Six"=6,
           "Ten"=10,
           "Three"=3,
           "Thrice"=3,
           "Twice"=2,
           "Twince"=2,
           "Two"=2,
           "10"=10,
           "2"=2,
           "3"=3),
         Pregnancy=cut(how_many,c(0,1,5,10,Inf),
                       c("once","2-5","6-10","No_preg")), 
         to_term=recode(
           to_term,
           "Eight"=8,
           "Five"=5,
           "Four"=4,
           "Nil"=12,
           "Once"=1,
           "One"=1,"0ne"=1,"one"=1,
           "Seven"=7,
           "Six"=6,
           "Ten"=10,
           "Three"=3,
           "Thrice"=3,
           "Twice"=2,
           "Twince"=2,
           "Two"=2,
           "10"=10,
           "2"=2,
           "3"=3,"Nine"=9),
         term_cat=cut(to_term,c(0,1,5,10,Inf),
                  c("One_child","2-5","6-10","no_child")) ,
         age_of_last=as.numeric(str_replace(age_of_last,"Nil","22")),
        ageoflast_cat=cut(age_of_last,c(0,1,5,10,15,20,Inf),
                c("One_year","1-5","6-10","11-15","16-20","none")),
         family_pla,
         which_one,
         how_long_20=recode(
           how_long_20,"1"=1,"2"=2,"3"=3,"5"=5,"6"=6,"Nil"=12 ,"<6M"=1,"NiL"=12),
         Vaginal_discharge=str_replace_all(color,c("NIL"="Nil")),
         il_10_quatile=ntile(il_10_avrg,3),
         il_10_quatile_cat=recode(il_10_quatile,"1"="firstq","2"="sec","3"="thir"),
         ifn_gam_quatile=ntile(ifn_gamm_avrg,3),
         ifn_gam_quatile_cat=recode(ifn_gam_quatile,"1"="firstq","2"="sec","3"="thir"),
         hsp_60_quatile=ntile(hsp_60_avrg,3),chlamydia_pos=ifelse(ig_g=="Pos"|ig_m=="Pos","Pos","Neg"),
         hsp_60_quatile_cat=recode(hsp_60_quatile,"1"="firstq","2"="sec","3"="thir")
  )

```

## **R Markdown of cytokine profile in infertile women: focus on dimension \n reduction**

### **Principal Component Analysis (PCA) for dimension reduction**
### **PCA for cluster recognition**
## **Preparing data for dimension and variable contribution**
### **Scree Plot**


```{r pressure}
cytokine_response<-newdata[newdata$group=="Infertile",c("il_10_avrg","ifn_gamm_avrg","hsp_60_avrg")]

# Run PCA
cytokine_pca<- prcomp(cytokine_response,scale=TRUE)

# Scree plot of variance

fviz_eig(cytokine_pca,
         addlabels = TRUE,
         ylim=c(0,70),
         main = "Cytokine screePlot"
         )

```

### PCA Plot

```{r}
# Biplot with Default Settings
fviz_pca_biplot(cytokine_pca)

# Biplot with labeled variables
fviz_pca_biplot(cytokine_pca,
                label = "var")
```

### Pattern Recognition

```{r}
# Biplot with customized colored groups and variables
fviz_pca_biplot(cytokine_pca,
                 label="var",addEllipses = TRUE,title="Cytokine PCA-Biplot",
                 habillage=newdata[newdata$group=="Infertile",]$chlamydia_pos                  ,col.var="black")+scale_color_manual(name="Chlamydia antigenemia",values=c("orange","purple"))+labs(x="PCA2 (55.6%)",y="PCA2 (29.1%)")
```

