---
title: "Udoma_Supplementary"
author: "Usman"
date: "2024-02-22"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
library(readxl)
library(janitor)
library(tidyverse)
library(finalfit)
library(dplyr)
library(MASS)
library(factoextra)
library(rstatix)
library(ggpubr)
#RESEARCH DATA-1.xlsx
#Infertile_type <- read_excel("C:/Users/Usman Ola/Documents
 #           /Chlamydia-Host_Immunology/RESEARCH DATA-1.xlsx",sheet="Sheet1")

Infertile_type<-RESEARCH_DATA_1 <- read_excel("RESEARCH DATA-1.xlsx", 
                              sheet = "Sheet1")
Infertile_type <- clean_names(Infertile_type)
names(Infertile_type) # All variables names are automagically cleaned!

```

## R Markdown

## Udoma's Supplementary

```{r cars}
# Analysis for Interferon gamma as Udoma

st.tst_gamma<-Infertile_type[c(1:109),]%>%
  mutate(diagnosis=recode(diagnosis,"TB"="TF"))%>%
  dunn_test(ifn_gamm_avrg~diagnosis,p.adjust.method="none")%>%
  add_xy_position(x="diagnosis")

cause_ifn<-Infertile_type[c(1:109),]%>%
  mutate(diagnosis=recode(diagnosis,"TB"="TF", "UTI"="UI"))%>%
  ggplot(aes(x=diagnosis,y=ifn_gamm_avrg))+
  geom_boxplot()+geom_point(position=position_jitter())+
  stat_pvalue_manual(st.tst_gamma, label = "p.adj.signif",hide.ns = TRUE,
                     tip.length = 0.01,color = "darkblue",size = 10,
                     y.position = c(500,520))+  
  labs(y = expression(bold("Interferon-"*gamma~"(pg/mL)")),
       x=expression(bold("Clinical daignostic cause of Infertility")))+
  theme_minimal()

# Analysis for Interleukin 10
st.tst_10<-Infertile_type[c(1:109),]%>%
  mutate(diagnosis=recode(diagnosis,"TB"="TF","UTI"="UI"))%>%
  dunn_test(il_10_avrg~diagnosis,p.adjust.method="none")%>%
  add_xy_position(x="diagnosis")

cause_il<-Infertile_type[c(1:109),]%>%
  mutate(diagnosis=recode(diagnosis,"TB"="TF","UTI"="UI"))%>%
  ggplot(aes(x=diagnosis,y=il_10_avrg))+
  geom_boxplot()+geom_point(position=position_jitter())+
  stat_pvalue_manual(st.tst_10, label = "p.adj.signif",hide.ns = TRUE,
                     tip.length = 0.01,color = "darkblue",size = 10,y.position = c(625)
                    )+  
  labs(y = expression(bold("Interleukin-10 (pg/mL)")),
       x=expression(bold("Clinical daignosis of Infertility")))+
  theme_minimal()

# Ct-HSP60 titer response along clinical diagnostic cause of infertility

st.tst_hsp60<-Infertile_type[c(1:109),]%>%
  mutate(diagnosis=recode(diagnosis,"TB"="TF","UTI"="UI"))%>%
  dunn_test(hsp_60_avrg~diagnosis,p.adjust.method="none")%>%
  add_xy_position(x="diagnosis")

cause_hsp<-Infertile_type[c(1:109),]%>%
  mutate(diagnosis=recode(diagnosis,"TB"="TF","UTI"="UI"))%>%
  ggplot(aes(x=diagnosis,y=hsp_60_avrg))+
  geom_boxplot()+geom_point(position=position_jitter())+
  stat_pvalue_manual(st.tst_hsp60, label = "p.adj.signif",hide.ns = TRUE,
                     tip.length = 0.01,color = "darkblue",size = 10,y.position = c(450))+  
  labs(y = expression(bold("Ct-Heat shock Protein-60 (pg/mL)")),
       x=expression(bold("Clinical daignostic cause of Infertility")))+
  theme_minimal()

ggarrange(cause_il,cause_ifn,cause_hsp,labels = c("A","B","C"))

```

## Including Plots

```{r, include=FALSE}
Chlamydia_Venn <- read_excel("C:/Users/Usman Ola/Downloads/Chlamydia Trichomatis.xlsx")

Chlamydia_logistic_reg <- clean_names(Chlamydia_Venn)
names(Chlamydia_logistic_reg) # All variables names are automagically cleaned!
newdata<-
  Chlamydia_logistic_reg[!Chlamydia_logistic_reg$how_long_7=="Nil",]%>%
  mutate(age_cat=cut(age,breaks = c(0,35,Inf),labels = c("<35",">35")),
          Marital_dur=ifelse(how_long_7=="1","First_Child","Children"),
         Marital_cat=cut(as.numeric(how_long_7),c(0,20,Inf),c("≤20",">20")),
         Times_mar=case_when(how_times=="Fouth"~"second",
                             how_times=="Third"~"second",
                             how_times=="First"~"first",
                             how_times=="Second"~"second"),
         wom_edu=str_replace(level_edu,"p","P"),
         husband_occ=case_when(
           husb_occ=="Leccturer"~"Lecturer",
           husb_occ=="Teacher"~"Lecturer",
           husb_occ=="Civil Serv"~"Civil_ser",
           husb_occ=="Lecturer"~"Lecturer",
           husb_occ=="Civil serv"~"Civil_ser",
           husb_occ=="Publicserv"~"Civil_ser",
           husb_occ=="Civilserv"~"Civil_ser",
           husb_occ=="Bussiness"~"Bussines",
           husb_occ=="Business"~"Bussines",
           husb_occ=="Carpenter"~"Artisan",
           husb_occ=="Artisan"~"Artisan",
           husb_occ=="Farmer"~"Farmer",
           TRUE~"others"),
         fam_type=str_replace_all(family_typ,c("mono"="Mono")),
         woman_occ=case_when(
           occup=="Teacher"~"Teacher",
           occup=="teacher"~"Teacher",
           occup=="Civil Serv"~"Civil_ser",
           occup=="House wife"~"House_wife",
           occup=="Civil serv"~"Civil_ser", 
           occup=="Civilserv"~"Civil_ser",
           occup=="Student"~"Student",
           occup=="Tailor"~"Artisan",
           occup=="Artisan"~"Artisan", 
           occup=="Farmer"~"Farmer",
           TRUE~"others"),
         woman_occ1=
           ifelse(woman_occ=="Teacher","Teacher","other"),
         woman_occ2=
           str_replace_all(woman_occ,c("Farmer"="others",                               "Student"="others","Teacher"="others","Artisan"="others")),
         woman_occ2f=factor(woman_occ2,levels=c("others","House_wife","Civil_ser")),any_preg=recode(any_preg,"No"="Primary_infert",
                         "Yes"="secondary_infert"),
         how_many=recode(
           how_many,
           "Eight"=8,
           "Five"=5,
           "Four"=4,
           "Nil"=0,
           "Once"=1,
           "One"=1,
           "Seven"=7,
           "Six"=6,
           "Ten"=10,
           "Three"=3,
           "Thrice"=3,
           "Twice"=2,
           "Twince"=2,
           "Two"=2,
           "10"=10,
           "2"=2,
           "3"=3),
         Pregnancy=cut(how_many,c(-Inf,0.9,1,5,10),
                       c("No_preg","once","2-5","6-10")), 
         to_term=recode(
           to_term,
           "Eight"=8,
           "Five"=5,
           "Four"=4,
           "Nil"=0,
           "Once"=1,
           "One"=1,"0ne"=1,"one"=1,
           "Seven"=7,
           "Six"=6,
           "Ten"=10,
           "Three"=3,
           "Thrice"=3,
           "Twice"=2,
           "Twince"=2,
           "Two"=2,
           "10"=10,
           "2"=2,
           "3"=3,"Nine"=9),
         term_cat=cut(to_term,c(-Inf,0.9,1,5,10),right=TRUE,
                  c("no_child","One_child","2-5","6-10"),.drop=FALSE) ,
         age_of_last=as.numeric(str_replace(age_of_last,"Nil","0")),
        ageoflast_cat=cut(age_of_last,c(-Inf,0.9,1,5,10,15,20),
                c("none","One_year","1-5","6-10","11-15","16-20")),
         family_pla,
         which_one,discomfort1=recode(discomfort,"Boil"="Nil"),
         how_long_20=recode(
           how_long_20,"1"=1,"2"=2,"3"=3,"5"=5,"6"=6,"Nil"=0 ,"<6M"=1,"NiL"=0),
         Vaginal_discharge=str_replace_all(color,
           c("NIL"="Nil","Brownish"="Reddish")),
        vaginal_discharge1=str_replace_all(Vaginal_discharge,
      c("Brownish"="Yellowish","Reddish"="Yellowish")),
         il_10_quatile=ntile(il_10_avrg,3),
         il_10_quatile_cat=recode(il_10_quatile,
          "1"="firstq","2"="sec","3"="thir"),
         ifn_gam_quatile=ntile(ifn_gamm_avrg,3),
         ifn_gam_quatile_cat=recode(ifn_gam_quatile,
          "1"="firstq","2"="sec","3"="thir"),
         hsp_60_quatile=ntile(hsp_60_avrg,3),
      chlamydia_pos=ifelse(ig_g=="Pos"|ig_m=="Pos","Pos","Neg"),
      hsp_60_quatile_cat=recode(hsp_60_quatile,
      "1"="firstq","2"="sec","3"="thir")
      )

```


```{r pressure}

stat_odour<-newdata%>%group_by(group)%>%
  dunn_test(il_10_avrg~odour,p.adjust.method="none")%>%
  add_xy_position(x="odour",group = "group")
stat_odour
stat_odour_1<-newdata%>%
  group_by(odour)%>%
  dunn_test(il_10_avrg~group,p.adjust.method="none")%>%
  add_xy_position(x="odour")
stat_odour_1
A_i<-newdata%>%ggplot(aes(x=odour,y=il_10_avrg,color=group))+
    geom_boxplot()+
  geom_point(position=position_jitter())+
  stat_pvalue_manual(stat_odour, label = "p.adj.signif",hide.ns = FALSE,tip.length = 0.01,color = "darkblue",size = 8,
                     y.position = c(630,660))+
  stat_pvalue_manual(stat_odour_1, 
  label = "p.adj.signif",hide.ns = FALSE,tip.length = 0.01,color = "darkblue",size = 8,y.position = c(530,530))+  labs(y = expression(bold("Interleukin-10 (pg/mL)")),x=expression(bold("Odour")))+theme_minimal()

A_i
```


```{r}
stat_odour_ifn<-newdata%>%group_by(group)%>%
  dunn_test(ifn_gamm_avrg~odour,p.adjust.method="none")%>%
  add_xy_position(x="odour",group = "group")
stat_odour_ifn
stat_odour_ifn1<-newdata%>%
  group_by(odour)%>%
  dunn_test(ifn_gamm_avrg~group,p.adjust.method="none")%>%
  add_xy_position(x="odour")
stat_odour_ifn1
A_ii<-newdata%>%
  ggplot(aes(x=odour,y=ifn_gamm_avrg,color=group))+
geom_boxplot()+geom_point(position=position_jitter())+
stat_pvalue_manual(stat_odour_ifn, label = "p.adj.signif",hide.ns = FALSE,tip.length = 0.01,color = "darkblue",size = 8,
                     y.position = c(630,660))+
  stat_pvalue_manual(stat_odour_ifn1, 
  label = "p.adj.signif",hide.ns = FALSE,tip.length = 0.01,color = "darkblue",size = 8,y.position = c(530,530))+  
  labs(y = expression(bold("Interferon-"*gamma ~"(pg/mL)")),x=expression(bold("Odour")))+theme_minimal()

A_ii
```


```{r}
ggarrange(A_i,A_ii,labels = c("A(I)","A(II)"),common.legend = TRUE)
```


```{r}

# stat_discharge<-newdata%>%group_by(group)%>%
#dunn_test(il_10_avrg~
#vaginal_discharge1,p.adjust.method="none")%>%
#add_xy_position(x="vaginal_discharge1")
# stat_discharge
stat_discharge_1<-newdata%>%
  group_by(vaginal_discharge1)%>%
  dunn_test(il_10_avrg~group,p.adjust.method="none")%>%
  add_xy_position(x="vaginal_discharge1",group = "group")
stat_discharge_1
B_i<-newdata%>%
  ggplot(aes(x=vaginal_discharge1,y=il_10_avrg,color=group))+
    geom_boxplot()+
  geom_point(position=position_jitter())+
  # stat_pvalue_manual(stat_discharge_1, label = "p.adj.signif",hide.ns = FALSE,tip.length = 0.01,color = "darkblue",size = 8,y.position = c(630,660,680))+
  stat_pvalue_manual(stat_discharge_1, label = "p.adj.signif",hide.ns = FALSE,tip.length = 0.01,color = "darkblue",size = 8,y.position = c(530,530,560))+  
  labs(y = expression(bold("Interleukin-10 (pg/mL)")),x=expression(bold("Vaginal Discharge")))+theme_minimal()

B_i


# Interferon gamma levels according vaginal discharge
stat_discharge_ifn1<-newdata%>%
  group_by(vaginal_discharge1)%>%
  dunn_test(ifn_gamm_avrg~group,p.adjust.method="none")%>%
  add_xy_position(x="vaginal_discharge1",group = "group")
stat_discharge_ifn1
B_ii<-newdata%>%
  ggplot(aes(x=vaginal_discharge1,y=ifn_gamm_avrg,color=group))+
    geom_boxplot()+geom_point(position=position_jitter())+
  # stat_pvalue_manual(stat_discharge_1, label = "p.adj.signif",hide.ns = FALSE,tip.length = 0.01,color = "darkblue",size = 8,y.position = c(630,660,680))+
  stat_pvalue_manual(stat_discharge_ifn1, 
  label = "p.adj.signif",hide.ns = FALSE,tip.length = 0.01,color = "darkblue",size = 8,y.position = c(330,330,360))+  
  labs(y = expression(bold("Interferon-"*gamma~" (pg/mL)")),x=expression(bold("Vaginal Discharge")))+
  theme_minimal()

B_ii
```

```{r}
ggarrange(B_i,B_ii,labels = c("B(I)","B(II)"),common.legend = TRUE)
```

### level of interferon-10 and Interferon gamma stratified according to discomfort Clinical presentation
```{r}

# stat_discomfort<-newdata%>%group_by(group)%>%dunn_test(il_10_avrg~vaginal_discharge1,p.adjust.method="none")%>%add_xy_position(x="vaginal_discharge1")
# stat_discharge
stat_discomfort_1<-newdata%>%
  group_by(discomfort1)%>%
  dunn_test(il_10_avrg~group,p.adjust.method="none")%>%
  add_xy_position(x="discomfort1",group = "group")
stat_discomfort_1
C_i<-newdata%>%ggplot(aes(x=discomfort1,y=il_10_avrg,color=group))+
    geom_boxplot()+geom_point(position=position_jitter())+
  # stat_pvalue_manual(stat_discharge_1, label = "p.adj.signif",hide.ns = FALSE,tip.length = 0.01,color = "darkblue",size = 8,y.position = c(630,660,680,700))+
  stat_pvalue_manual(stat_discomfort_1, label = "p.adj.signif",hide.ns = FALSE,tip.length = 0.01,color = "darkblue",size = 8,y.position = c(530,530,560))+ scale_x_discrete(limits=c("Nil","Itching","Pain"))+
  labs(y = expression(bold("Interleukin-10 (pg/mL)")),x=expression(bold("Discomfort")))+theme_minimal()

C_i


# Interferon gamma levels according vaginal discharge
stat_discomfort_ifn1<-newdata%>%
  group_by(discomfort1)%>%
  dunn_test(ifn_gamm_avrg~group,p.adjust.method="none")%>%
  add_xy_position(x = "discomfort1")
stat_discomfort_ifn1
C_ii<-newdata%>%ggplot(aes(x=discomfort1,y=ifn_gamm_avrg,color=group))+
    geom_boxplot()+geom_point(position=position_jitter())+
  # stat_pvalue_manual(stat_discharge_1, label = "p.adj.signif",hide.ns = FALSE,tip.length = 0.01,color = "darkblue",size = 8,y.position = c(630,660,680))+
stat_pvalue_manual(stat_discomfort_ifn1, label = "p.adj.signif",hide.ns = FALSE,tip.length = 0.01,color = "darkblue",size = 8,y.position = c(330,330,360))+ scale_x_discrete(limits=c("Nil","Itching","Pain"))+ 
  labs(y = expression(bold("Interferon-"*gamma~" (pg/mL)")),x=expression(bold("Discomfort")))+theme_minimal()

C_ii
```

```{r}
ggarrange(C_i,C_ii,labels = c("C(I)","C(II)"),common.legend = TRUE)
```

```{r}
clinical_diagnostic_infertility_type<-Infertile_type[c(1:109),]%>%mutate(diagnosis=recode(diagnosis,"TB"="TF"),any_preg=recode(any_preg,"No"="Primary_infert", "Yes"="secondary_infert"))%>%group_by(any_preg,ig_m,ig_g)%>%count(diagnosis)%>%pivot_wider(names_from=any_preg,values_from=n)
```


```{r}
# Analysis for Interferon gamma as Udoma

st.tst_gamma<-Infertile_type[c(1:109),]%>%
  dunn_test(ifn_gamm_avrg~diagnosis,p.adjust.method="none")%>%
  add_xy_position(x="diagnosis")

Infertile_type[c(1:109),]%>%mutate(diagnosis=recode(diagnosis,"UTI"="UI"))%>%
  ggplot(aes(x=diagnosis,y=ifn_gamm_avrg))+
  geom_boxplot()+geom_point(position=position_jitter())+
  stat_pvalue_manual(st.tst_gamma, label = "p.adj.signif",hide.ns = TRUE,
                     tip.length = 0.01,color = "darkblue",size = 10,
                     y.position = c(500,520))+  
  labs(y = expression(bold("Interferon-"*gamma~"(pg/mL)")),
       x=expression(bold("Clinical daignostic cause of Infertility")))+
  theme_minimal()

# Analysis for Interleukin 10st.tst_10<-Infertile_type[c(1:109),]%>%
# st.tst_10<-Infertile_type[c(1:109),]%>%
# st.tst_10<-Infertile_type[c(1:109),]%>%
# st.tst_10<-Infertile_type[c(1:109),]%>%
st.tst_10<-Infertile_type[c(1:109),]%>%
  mutate(diagnosis=recode(diagnosis,"TB"="TF"))%>%
  dunn_test(il_10_avrg~diagnosis,p.adjust.method="none")%>%
  add_xy_position(x="diagnosis")

Infertile_type[c(1:109),]%>%
  mutate(diagnosis=recode(diagnosis,"TB"="TF"))%>%
  ggplot(aes(x=diagnosis,y=il_10_avrg))+
  geom_boxplot()+geom_point(position=position_jitter())+
  stat_pvalue_manual(st.tst_10, label = "p.adj.signif",hide.ns = TRUE,
                     tip.length = 0.01,color = "darkblue",size = 10,y.position = c(625)
                    )+  
  labs(y = expression(bold("Interleukin-10 (pg/mL)")),
       x=expression(bold("Clinical daignosis of Infertility")))+
  theme_minimal()

# Ct-HSP60 titer response along clinical diagnostic cause of infertility

st.tst_hsp60<-Infertile_type[c(1:109),]%>%
  mutate(diagnosis=recode(diagnosis,"TB"="TF"))%>%
  dunn_test(hsp_60_avrg~diagnosis,p.adjust.method="none")%>%
  add_xy_position(x="diagnosis")

Infertile_type[c(1:109),]%>%mutate(diagnosis=recode(diagnosis,"UTI"="UI"))%>%
  mutate(diagnosis=recode(diagnosis,"TB"="TF"))%>%
  ggplot(aes(x=diagnosis,y=hsp_60_avrg))+
  geom_boxplot()+geom_point(position=position_jitter())+
  stat_pvalue_manual(st.tst_hsp60, label = "p.adj.signif",hide.ns = TRUE,
                     tip.length = 0.01,color = "darkblue",size = 10,y.position = c(450))+  
  labs(y = expression(bold("Ct-Heat shock Protein-60 (pg/mL)")),
       x=expression(bold("Clinical daignostic cause of Infertility")))+
  theme_minimal()

```

